workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
        JVM_OPTS: -Xmx3200m
    steps:
        - checkout
        - run:
            name: Chmod permissions
            command: chmod +x ./gradlew
        - run:
            name: Upload Archives
            command: ./gradlew uploadArchives
        - store_artifacts:
             path: ./build/distributions
        - persist_to_workspace:
            root: build
            paths:
              - distributions
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /build
      - run:
          name: Publish Release on GitHub
          environment:
              CIRCLE_TAG: lokalise-plugin-1.3
          command: |
              ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1}
               -delete lokalise-plugin-1.3 /build/distributions