workflows:
  version: 2
  build_publish_release:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-plugin-in-gradle:
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - publish-plugin-in-gradle
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
        JVM_OPTS: -Xmx3200m
    steps:
        - checkout
        - run:
            name: Chmod permissions
            command: chmod +x ./gradlew
        - run:
            name: Upload Archives
            command: ./gradlew uploadArchives
        - store_artifacts:
            path: ./artifacts/com/github/likandr/lokalise-plugin
        - persist_to_workspace:
            root: artifacts
            paths:
              - com/github/likandr/lokalise-plugin
        - store_artifacts:
             path: ./build/distributions
        - persist_to_workspace:
            root: build
            paths:
              - distributions
  publish-plugin-in-gradle:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - attach_workspace:
              at: /artifacts/com/github/likandr/lokalise-plugin
        - run:
              name: Login
              command: ./gradlew login
        - run:
              name: Publish plugin
              command: ./gradlew publishPlugins
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    environment:
        DIR_ARTIFACTS: /build/distributions
        CIRCLE_TAG: 1.0
    steps:
      - attach_workspace:
          at: /build
      - run:
          name: Publish Release on GitHub
          command: |
              ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete v${CIRCLE_TAG} ${DIR_ARTIFACTS}