version: 2
jobs:
  build:
      docker:
        - image: circleci/android:api-28-alpha
      steps:
        - checkout
        - run:
           name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
           command: sudo chmod +x ./gradlew
        - run:
            name: Upload Archives
            command: ./gradlew uploadArchives
#  upload-artifact:
#    docker:
#      - image: circleci/openjdk:8-jdk
#    working_directory: ~/repo
#    steps:
#      - checkout
#      - run: mvn dependency:go-offline
#      - run:
#          name: maven build
#          command: |
#            mvn clean install
#      - run:
#          name: Install jFrog CLI
#          command: curl -fL https://getcli.jfrog.io | sh
#      - run:
#          name: Push to Artifactory
#          command: |
#            ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive=false
#            ./jfrog rt u <path/to/artifact> <artifactory_repo_name> --build-name=<name_you_give_to_build> --build-number=$CIRCLE_BUILD_NUM
#            ./jfrog rt bce <name_you_give_to_build> $CIRCLE_BUILD_NUM  # collects all environment variables on the agent
#            ./jfrog rt bp <name_you_give_to_build> $CIRCLE_BUILD_NUM  # attaches ^^ to the build in artifactory

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
#      - upload-artifact

